version: 2.1

orbs:
  android: circleci/android@2.3.0
jobs:
  test:
    description: Runs unit tests and instrumented tests on the Services app
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1

    steps:
      - checkout
      - run:
          name: Install OpenJDK 8
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-8-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
            echo 'export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"' >> $BASH_ENV
            java -version
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew

      - run:
          name: Update Package list
          command: sudo apt-get update
      - run:
          name: Install the latest Android SDK
          command: |
            sdkmanager --update
      - run:
          name: show gradle tasks
          command: ./gradlew tasks
      - android/create-avd:
          avd-name: customavd
          install: true
          system-image: system-images;android-28;default;x86_64
          additional-args: --sdcard 2048M

      - android/start-emulator:
          avd-name: customavd
          no-window: true
          restore-gradle-cache-prefix: v1
          post-emulator-launch-assemble-command: ./gradlew installDebug
      - run:
          name: Check emulator status
          command: |
            adb devices
            adb shell getprop sys.boot_completed
            echo "if sys.boot_completed = 1 means emualtor has finished booting"
      - run:
          name: show installed packages
          command: adb shell pm list packages
      - run:
          name: install the services app on the emulator
          command: adb install ${CIRCLE_WORKING_DIRECTORY}/build/outputs/apk/debug/app-debug.apk
      - run:
          name: show installed packages
          command: adb shell pm list packages

     
      # - android/run-tests:
      #     test-command: ./gradlew test

      - android/run-tests:
          test-command: ./gradlew grantPermissionForODkApp connectedAndroidTest
      - android/save-gradle-cache:
          cache-prefix: v1

  build:
    docker:
      - image: cimg/android:2023.06
    steps:
      - checkout
      - run:
          name: Install OpenJDK 8
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-8-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
            echo 'export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"' >> $BASH_ENV
            java -version

      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew
      - android/restore-gradle-cache:
          cache-prefix: v1

      - run:
          name: Echo Java home
          command: |
            echo $JAVA_HOME  

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - android/save-gradle-cache:
          cache-prefix: v1
      - run:
          name: Build Services
          command: ./gradlew assemble

workflows:
  build-test-deploy-workflow:
    jobs:
      # - build
      - test
      # - test:
      #     requires:
      #       - build
      # - deploy:
      #     requires:
      #       - build
      #       - test



