version: 2.1

orbs:
  android: circleci/android@2.4.0
jobs:
  test:
    description: Runs unit tests and instrumented tests on the Android Common
    executor:
      name: android/android-machine
      resource-class: xlarge
      tag: 2024.01.1

    steps:
      - checkout
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew

      - android/create-avd:
          avd-name: avd
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: avd
          no-window: true
          restore-gradle-cache-prefix: v2
          post-emulator-launch-assemble-command: ./gradlew installSnapshotDebug 
      - android/disable-animations
      - android/run-tests:
          test-command: ./gradlew testSnapshotDebugUnitTest
      - android/run-tests:
          test-command: ./gradlew grantPermissionForODKXApp connectedSnapshotDebugAndroidTest
      - android/save-gradle-cache:
          cache-prefix: v1
      - store_artifacts:
          name: Store Test Results
          path: services_app/build/outputs/androidTest-results
      - store_artifacts:
          name: Store Test Reports
          path: services_app/build/reports

  build:
    docker:
      - image: cimg/android:2024.01
    steps:
      - checkout
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew
      - android/restore-gradle-cache:
          cache-prefix: v1
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - android/save-gradle-cache:
          cache-prefix: v1
      - run:
          name: Build Services
          command: ./gradlew assembleSnapshotDebug

      - persist_to_workspace:
          root: .
          paths:
            #- build/outputs/apk/snapshot/debug/services_app-snapshot-debug.apk
            - services_app/build/outputs/apk/snapshot/debug/services_app-snapshot-debug.apk

  deploy:
    docker:
      - image: cimg/python:3.12.3
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Github Releases CLI
          command: pip install githubrelease
      - run:
          name: Create Github Releases and Upload APK
          command: |
            APK_FILE="services_app/build/outputs/apk/snapshot/debug/services_app-snapshot-debug.apk"
            SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            TAG_NAME="snapshot-$SHORT_HASH"
                        
            githubrelease release $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME create $TAG_NAME --name $TAG_NAME --body "Automated release by CircleCI"
            githubrelease asset $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME upload $TAG_NAME $APK_FILE
        

workflows:
  build-test-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - test:
          requires:
            - build
